---
title: "final"
format: html

#knitr::opts_chunk$set(fig.width = 10, fig.height = 5)

---
initial set up 
```{r}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)

install.packages("tidyverse")
install.packages("gt")
install.packages("janitor")
install.packages("dplyr")
install.packages("here")
install.packages("lubridate")
install.packages("readxl")
install.packages("MuMIn")
install.packages("DHARMa")
install.packages("fs")


library(tidyverse)  

library(gt)

library(janitor)

library(dplyr)

library(here) 

library(knitr)

library(lubridate) 

library(readxl)  

library(MuMIn) 

library(DHARMa) 

library(fs) 
```


Reading in Data 
```{r}
sst <- read.csv(here::here("data", "SST_update2023.csv")) # reading in data 

nest_boxes <- read.csv(here::here("data", "occdist.csv"))

```


Problem 2 

(a) Cleaning and Summarizing Data 
```{r}
sst_clean <- sst |> #beginning the sst dataframe
  mutate (
    date = ymd(date), # making date an object 
    month = month(date, label = TRUE, abbr = TRUE) |> #creating a column for months
              factor(levels = month.abb, ordered = TRUE), #ordered factor for months 
    year = (year(date)) #creating a column for years 
    ) |> 
      
    filter(year >= 2018, year <= 2023) |> #filtering years to include 2018 - 2023 
    mutate(
      year = factor(year) #convert to factor 
    ) |> 
    group_by(year, month) |> # group data by the year and the month 
    summarize(mean_monthly_sst = mean(temp, na.rm = TRUE)) |> #summarize the mean monthly sst 
    ungroup() #remove grouping 

slice_sample(sst_clean, n = 5) # show 5 random rows 

str(sst_clean) # show structure of the data 


```


(b) Visualize the Data 
```{r, fig.height = 5, fig.width = 10 } 

ggplot(data = sst_clean, #creating visualization, using sst_clean data frame
       aes(x = month, # month is the x axis 
           y = mean_monthly_sst, # meanly monthly sst is the y axis 
           group = year, # group data by year 
           color = year)) + #color data by year
  
  geom_line(linewidth = 0.5) + #adjusting line width 
  geom_point(size = 1.5) + # adjusting point size
  
  scale_color_manual(values = c( #color the lines different shades of blue
    "2018" = "paleturquoise",
    "2019" = "skyblue",
    "2020" = "steelblue",
    "2021" = "royalblue",
    "2022" = "blue3",
    "2023" = "blue4"  
  )) + 
  
  labs(x = "Month", # editing x-axis label title
     y = "Mean monthly sea surface temperature (°C)", # editing y axis label title
     color = "Year" # legend title 
     ) + 

theme_minimal(base_size = 12) + #apply minimal theme, font size 12 
theme(
  panel.background = element_rect(fill = "white", color = NA), # create a white background 
  panel.grid.major = element_blank(), # remove grid line colors
  panel.grid.minor = element_blank(), # remove grid line colors 
  panel.border = element_rect(color = "gray", fill = NA, linewidth = 1), # add a border color 
  legend.position = c(0.05, 0.95), # positioning the legend 
  legend.justification = c(0,1), # positioning legend
  legend.background = element_rect(fill = "white", color = "gray"), # background and border colors for the legend
  axis.line = element_blank() # remove axis lines
)
```

Problem 3

```{r, cleaning data, echo=FALSE, message=FALSE, results='hide'}
nest_boxes_clean <- nest_boxes |> #cleaning the dataframe 
  clean_names() |> #clean names 
  mutate( # modifying variables 
    box_occupant = as_factor(box_occupant),# convert box_occupant to a factor 
    box_occupant = fct_relevel(box_occupant, # ordering the box_occupant factors 
                               "swift parrot",
                               "common starling",
                               "tree martin",
                               "empty"),
    season = factor(season, levels = c("2016", "2019")), # convert season to an ordered factor 
    edge_distance = as.numeric(edge_distance) # edge_distance as a numeric variable 
  ) |> 
  
  select(  # selecting the columns we want 
    box_occupant, # box occupant 
    edge_distance, # box distance 
    season, # season/year of observation 
    sp, cs, e, tm) # species indicators or unoccupied 
  
nest_boxes_clean |> slice_sample(n=5) # selection of 5 random rows 
str(nest_boxes_clean) # displaying strucutre of cleaned dataset 
```

```{r, visualizing data, echo=FALSE, message=FALSE, warning=FALSE, output=FALSE, results='hide', fig.show='hide'}

ggplot(data = nest_boxes_clean, # using the nest_boxes_clean data 
       aes(x = season, # x axis is the 
           y = edge_distance,
           color = season)) + 
  
  geom_jitter(width = 0.1, 
              height = 0, 
              shape = 21,
              alpha = 0.6,
              fill = "white")+
  
  stat_summary(geom = "point",
               fun = mean,
               size = 2,
               color = "black")

```

(a) Response Variable

(b) Purpose of Study

(c) Difference in "Seasons"

(d) Table of Models
```{r model-table, echo=TRUE}

model_table <- data.frame(
  Model = 0:3,
  Season = c("", "X", "X", ""),
  Edge_Distance = c("", "X", "", "X"),
  Predictor_list= c(
    "No predictors (null model)",
    "All predictors (full model)",
    "Season only",
    "Distance to Forest Edge Only"
),

stringsAsFactors = FALSE

)

kable(model_table, 
      col.names = c("Model Number", "Season", "Distance to Forest Edge", "Predictor List"),
      caption = "Table 1. Summary of Models.",
      align = c("c","c","c","l")
)

model_table
```


(e) Run the models 
```{r model-fitting}
# Model 0 : Null model 
model0 <- glm(sp ~ 1, # formula 
              data = nest_boxes_clean, # data  
              family = "binomial") # distribution 

# Model 1: Saturated model with interaction 
model1 <- glm(sp ~ edge_distance + season, # formula
              data = nest_boxes_clean, # data
              family = "binomial") # distribution


# Model 2: Season Only 
model2 <- glm(sp ~ season, # formula
              data = nest_boxes_clean, # data
              family = "binomial") # distribution


#Model 3: Distance Only
model3 <- glm(sp ~ edge_distance, # formula 
              data = nest_boxes_clean, # data 
              family = "binomial") # distribution 

```



(f) Check diagnostics

```{r diagnostics, message=FALSE}

# diagnostics for model 0 
plot(
  simulateResiduals(model0))

# diagnostics for model 1 
plot(
  simulateResiduals(model1))


# diagnostics for model 2 
plot(
  simulateResiduals(model2))

# diagnostics for model 3
plot(
  simulateResiduals(model3))


```


(g) Select best model 

```{r model-selection}

AICc(
  model0,
  model1,
  model2,
  model3
  ) |> 
  arrange(AICc)

```


(h) visualize model predictions

(i) figure caption

(j) Calculate model predictions

(k) interpret your results

